dist: trusty

install:
  # Install conan
  - pip install --user -q conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build=missing
  - cmake ..
  - cmake --build .
  - ./bin/test_hello

matrix:
  include:
    - addons:
        apt:
          source:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CXX=g++-5 CC=gcc-5
