build: false

platform: x64

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user # Create the conan data directory

build_script:
  - mkdir build && cd build
  - conan install .. --build
  - cmake .. -G "Visual Studio 14 2015 Win64"
  - cmake --build . --config Release

test_script:
  - ./bin/test_hello
